<a href="https://colab.research.google.com/github/ulricp/learnPython/blob/main/try_some_stuff.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [16]:
import numpy as np
arr = np.array([[1,2,3]])
b = arr + [4,5,6]
print(b)

[[5 7 9]]
